### ISSUE TITLE
Incrementing the version number is a mess

### ISSUE THREAD

**Issue by mgillis** [AmbitionFramework/almanna#2]

**Comment by nmelnick** [comment]
Closing this one out due to commit 7b9b0dc, with the transition to the Meson build system. Version is now claimed once in /meson.build, and supports incrementing the minor version without affecting the API version. The dependencies at src/libalmanna/almanna-0.1.deps will need to be renamed when the API moves to a new major version.

**Comment by mgillis** [comment]
I've been checking this page every day for 4 1/2 years. Thank you. Now I
can sleep.
